# Generated by Django 5.0.6 on 2024-05-15 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_service_remove_user_date_joined_user_sub_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='passengers',
            field=models.ManyToManyField(blank=True, related_name='service_passengers', to=settings.AUTH_USER_MODEL),
        ),
    ]
