# Generated by Django 5.0.6 on 2024-05-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='datetime',
            field=models.DateField(blank=True),
        ),
    ]
